### ISSUE TITLE
TypeScript Definition Files

### ISSUE THREAD

**Issue by wahmedswl** [sagiegurari/simple-oracledb#18] opened 2016-12-14 10:00 UTC
#### Problem Description

Hi, it would be great to have TypeScript Definition Files as official oracle driver have that and it helps in rich experience in VSCode.

Thanks

**Comment by cjbj** [comment] 2016-12-14 10:05
Duplicate of #169 - this links to the TypeScript definitions..  When 1.12 is released to npm, I was going to nude @bigous to see if he can update them

**Comment by cjbj** [comment] 2016-12-14 10:05
Crap - wrong repo! Sorry @sagiegurari

**Comment by sagiegurari** [comment] 2016-12-14 10:13
In this repo, I don't think this will happen.
Too much maintenance because I got a lot of apis and I don't want to manage that.
You might want to look like @cjbj stated at oracle/node-oracledb#169 and see there, which basically an external contributor created that definition and submitted it to https://github.com/DefinitelyTyped/DefinitelyTyped
So you can do the same and I can reference your definitions file in my docs.

**Closed** 2016-12-14 18:35 UTC
